from openai import OpenAI
import json

client = OpenAI()

rust_docs = """
Here is a summary of some Vec<T> functions in Rust:

1. `fn new() -> Vec<T>`: Creates a new, empty vector.
2. `fn with_capacity(capacity: usize) -> Vec<T>`: Creates a new
vector with the specified capacity.
3. `fn push(&mut self, value: T)`: Appends an element to the back of the vector.
4. `fn pop(&mut self) -> Option<T>`:
Removes the last element from the vector and returns it, or None if it is empty.
5. `fn insert(&mut self, index: usize, element: T)`: Inserts
an element at the specified index, shifting all elements after it to the right.
6. `fn remove(&mut self, index: usize) -> T`: Removes and returns
the element at the specified index, shifting all elements after it to the left.
7. `fn len(&self) -> usize`: Returns the number of elements in the vector
8. `fn is_empty(&self) -> bool`: Returns true if the vector contains no elements.
9. `fn clear(&mut self)`: Removes all elements from the vector.
10. `fn resize(&mut self, new_len: usize, value: T)`: Resizes the vector
so that its length is equal to new_len.
"""

def get_rust_docs():
    return rust_docs

tools = [
    {
        "type": "function",
        "name": "get_rust_docs",
        "description": "Returns a summary of Vec<T> functions in Rust.",
    }
]

user_query = "How do I remove the last element from a Vec<T> in Rust?"

input_list = [
    {
        "role": "system",
        "content": """
            You are a Rust documentation assistant. Respond to the user queries
            about Vec<T> in Rust exclusively using the provided functions in the tools.
            Using any other information is not allowed.

            Respond to the user with the relevant function signature and its documentation,
            modified as necessary to fit the user's query.
        """
    },
    {"role": "user", "content": user_query},
]

response = client.responses.create(
    model="gpt-5",
    input=input_list,
    tools=tools,
)

function_call = None
function_call_arguments = None
input_list += response.output

for item in response.output:
    print(f"Item: {item}")
    if item.type == "function_call":
        function_call = item
        function_call_arguments = json.loads(item.arguments)

if function_call:
    input_list.append({
        "type": "function_call_output",
        "call_id": function_call.call_id,
        "output": json.dumps({
            "functions": get_rust_docs()
        })
    })

    response = client.responses.create(
        model="gpt-5",
        instructions="Respond only with the relevant portion of the documentation generated by a tool.",
        tools=tools,
        input=input_list,
    )

print(f"Final input: {input_list}")
print(f"Final output: {response.model_dump_json(indent=2)}\n {response.output_text}")
